autoclose_curlybraces: true
autoclose_doublequotes: true
autoclose_parentheses: true
autoclose_singlequotes: true
autoclose_squarebrackets: true
font_color: '#24292E'
font_family: monospace
font_size: 12
horizontal_scrollbar_active_bg: '#8a7575'
horizontal_scrollbar_color: '#383030'
horizontal_scrollbar_trough_color: '#2e2724'
horizontal_scrollbar_width: 8
insertion_blink: false
insertion_color: '#75715E'
menu_active_bg: '#FFFFFF'
menu_active_fg: '#24292E'
menu_bg: '#FFFFFF'
menu_fg: '#6A737D'
menubar_active_bg: '#FFFFFF'
menubar_active_fg: '#24292E'
tab_size: 4
text_bottom_lineheight: '1'
text_selection_bg: '#1b444f'
text_top_lineheight: '1'
text_wrap: none
textarea_background_color: '#FFFFFF'
textarea_border: 0
textarea_padding_x: '5'
textarea_padding_y: '5'
vertical_scrollbar_active_bg: '#8a7575'
vertical_scrollbar_color: '#383030'
vertical_scrollbar_trough_color: '#2e2724'
vertical_scrollbar_width: 8
